[project]
name = "irene-voice-assistant"
version = "12.0.0"
description = "Ирина - русский голосовой ассистент для работы оффлайн. Поддерживает скиллы через плагины."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    # Core audio and speech processing
    "vosk>=0.3.45",
    "vosk-tts>=0.3.52", 
    "sounddevice",
    "soundfile",
    "audioplayer",
    "pyttsx3>=2.90",
    
    # Text processing and NLP
    "requests", 
    "python-dateutil>=2.6.0",
    "wikipedia-api>=0.5.4",
    
    # UI and console
    "termcolor>=1.1.0",
    
    # AI and API integrations
    "openai==0.28.0",
    "elevenlabs==1.0.3",
    
    # System interaction
    "pyautogui",
    
    # File system
    "fsspec==2023.1.0",
]

[project.optional-dependencies]
# Web server dependencies for API mode
web = [
    "fastapi>=0.81.0",
    "uvicorn[standard]>=0.18.3",
    "starlette>=0.19.1",
]

# UI with gradio (can cause dependency conflicts)
ui = [
    "gradio>=4.0.0",
]

# Executable runner minimal dependencies
minimal = [
    "vosk>=0.3.45",
    "pyttsx3==2.90",
    "termcolor>=1.1.0",
    "sounddevice",
    "soundfile", 
    "requests",
    "audioplayer",
    "python-dateutil",
]

# Development dependencies
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0", 
    "black>=22.0.0",
    "isort>=5.0.0",
    "flake8>=4.0.0",
    "mypy>=0.900",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=22.0.0", 
    "isort>=5.0.0",
    "flake8>=4.0.0",
    "mypy>=0.900",
]

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | eng_to_ipa
  | lingua_franca
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
exclude = [
    "eng_to_ipa/",
    "lingua_franca/",
    "model/",
]
