# ============================================================
# IRENE VOICE ASSISTANT - API-ONLY CONFIGURATION PROFILE
# ============================================================
# Server deployment configuration for API-only operation.
# No audio components, optimized for web services and integrations.
# Perfect for cloud deployments and microservice architectures.

[core]
name = "Irene"
version = "13.0.0"
debug = false
log_level = "INFO"
language = "en-US"
timezone = "UTC"

# Runtime performance settings for server
max_concurrent_commands = 50
command_timeout_seconds = 15.0
context_timeout_minutes = 10

# Monitoring and metrics enabled for production
enable_metrics = true
metrics_port = 9090
enable_profiling = false

# ============================================================
# ASSET MANAGEMENT - Server Storage
# ============================================================
[assets]
models_root = "./models"
cache_root = "./cache"
data_root = "./data"
credentials_root = "./credentials"

# ============================================================
# COMPONENT SYSTEM - Text Processing Only
# ============================================================
[components]
enabled = ["llm", "nlu", "text_processor"]
disabled = ["audio", "tts", "asr", "voice_trigger"]

# ============================================================
# WORKFLOW SYSTEM - No Voice Workflows
# ============================================================
[workflows]
enabled = []  # API-driven operation only
disabled = ["voice_assistant", "continuous_listening"]

# ============================================================
# INPUT/OUTPUT SYSTEM - Web API Only
# ============================================================
[inputs]
enabled = ["web", "cli"]
disabled = ["microphone"]
default = "web"

[outputs]
enabled = ["web", "text"]
disabled = ["tts"]
default = "web"

# ============================================================
# PROVIDER SYSTEM - Text and Cloud Services Only
# ============================================================
[providers.audio]
enabled = []  # No audio providers
disabled = ["sounddevice", "console", "aplay", "audioplayer", "simpleaudio"]

[providers.tts]
enabled = []  # No TTS providers for API-only
disabled = ["elevenlabs", "pyttsx", "silero_v3", "silero_v4", "vosk_tts", "console"]

[providers.asr]
enabled = []  # No ASR providers for API-only
disabled = ["vosk", "whisper", "google_cloud"]

[providers.llm]
# Cloud LLM providers for text processing
enabled = ["openai", "anthropic"]
disabled = ["vsegpt"]
default = "openai"
fallback_providers = []

[providers.voice_trigger]
enabled = []  # No voice trigger
disabled = ["openwakeword", "microwakeword"]

[providers.nlu]
# Text-based NLU for intent recognition
enabled = ["rule_based"]
disabled = ["spacy"]  # Reduce dependencies
default = "rule_based"
fallback_providers = []

[providers.text_processing]
# Full text processing for API requests
enabled = ["general_text_processor", "number_text_processor"]
disabled = ["asr_text_processor", "tts_text_processor"]
default = "general_text_processor"

# ============================================================
# INTENT SYSTEM - Full Intent Processing
# ============================================================
[intents]
enabled = true
confidence_threshold = 0.7
fallback_handler = "conversation"

[intents.handlers]
# All intent handlers for rich API functionality
enabled = ["conversation", "greetings", "timer", "datetime", "system"]
disabled = ["train_schedule"]  # Remove specialized handlers

# ============================================================
# PLUGIN SYSTEM - Service Plugins
# ============================================================
[plugins]
enabled = ["async_service_demo"]
disabled = ["random_plugin"]  # Keep only service-oriented plugins

# ============================================================
# WEB API - Production Web Interface
# ============================================================
[webapi]
enabled = true
host = "0.0.0.0"
port = 8000
cors_enabled = true
static_files = true

# Rate limiting for production
rate_limit_enabled = true
rate_limit_requests = 100
rate_limit_window = 60

# Security settings
api_key_required = true
https_redirect = true

# ============================================================
# PROVIDER CONFIGURATIONS - API Optimized
# ============================================================

# OpenAI Configuration
[providers.llm.openai]
api_key = "${OPENAI_API_KEY}"
model = "gpt-3.5-turbo"  # Faster model for API responses
max_tokens = 100
temperature = 0.5
timeout = 10.0

# Anthropic Configuration
[providers.llm.anthropic]
api_key = "${ANTHROPIC_API_KEY}"
model = "claude-3-haiku-20240307"  # Fastest model
max_tokens = 100
timeout = 10.0

# Rule-based NLU Configuration
[providers.nlu.rule_based]
confidence_threshold = 0.8
case_sensitive = false
fuzzy_matching = true 