# Irene Voice Assistant Configuration - Monitoring Example
# This configuration enables Phase 3 monitoring and analytics features

[system]
name = "Irene Voice Assistant"
version = "v13.0.0"
log_level = "INFO"

# ============================================================
# COMPONENT CONFIGURATIONS - Provider Management
# ============================================================

# Phase 3 Monitoring Component
[monitoring]
enabled = true
# Phase 3.1: User Notification System
notifications_enabled = true
notifications_default_channel = "log"
notifications_tts_enabled = true

# Phase 3.2: Metrics and Monitoring
metrics_enabled = true
metrics_monitoring_interval = 300
metrics_retention_hours = 24

# Phase 3.3: Memory Management
memory_management_enabled = true
memory_cleanup_interval = 1800
memory_aggressive_cleanup = false

# Phase 3.4: Debug Tools
debug_tools_enabled = true
debug_auto_inspect_failures = true
debug_max_history = 1000

# Phase 3.5: Analytics Dashboard
analytics_dashboard_enabled = true
analytics_web_port = 8081
analytics_refresh_interval = 30

# Required components for monitoring integration
[intent_system]
enabled = true

[tts]
enabled = true
default_provider = "console"
fallback_providers = ['console']

[audio]
enabled = true
default_provider = "console"
fallback_providers = ['console']

# Optional components (enable as needed)
[asr]
enabled = false

[llm]
enabled = false

[voice_trigger]
enabled = false

[nlu]
enabled = false

[text_processor]
enabled = false

# ============================================================
# PROVIDER CONFIGURATIONS - Individual Provider Settings
# ============================================================
[providers.tts]
console = { enabled = true }

[providers.audio]
console = { enabled = true }

# ============================================================
# INTENT HANDLERS - Enable handlers that have fire-and-forget actions
# ============================================================
# Note: Fire-and-forget is implemented in the handler code, not configuration
[intents]
conversation = true
timer = true
audio_playback_handler = true
voice_synthesis_handler = true
system = true

# ============================================================
# WORKFLOWS - Processing Pipeline Configuration
# ============================================================
[workflows]
unified_voice_assistant = true

# ============================================================
# INPUT SOURCES - Data Entry Points
# ============================================================
[inputs]
cli = true
web = false
